/**
 * Equoria-ke6ob — Sentinel-positive proof for the backend/eslint.config.mjs
 * runtime-artifact `ignores` exclusions.
 *
 * The defect (sibling of Equoria-pfn3p, which fixed the same exposure in
 * backend/.prettierignore): scripts/doctrine-checks/check-backend-lint-and-format.mjs
 * runs `eslint . --quiet` from cwd=backend/. ESLint's flat-config `ignores`
 * are the ONLY exclusion mechanism here — unlike git, eslint does NOT consult
 * any .gitignore. The gitignored runtime dirs (load-results/, test-results/,
 * the coverage variants, .jest-cache/) are regenerated by load/test/coverage runs and
 * are NEVER committed, but any machine-emitted .js/.mjs they contain (e.g. a
 * coverage HTML/JS bundle, a load-driver helper) would be linted. Because a
 * clean CI checkout has none of these files (CI stays green) but a LOCAL run
 * does, an eslint error in a never-shipped artifact turns the LOCAL doctrine
 * suite red on code the project never ships. Fix: list these dirs in the
 * eslint config's global `ignores`.
 *
 * This sentinel runs the REAL eslint CLI from cwd=backend/ against the REAL
 * backend/eslint.config.mjs — exactly as the doctrine check does — and proves
 * BOTH arms, so the fix can neither silently weaken (ignore real source) nor
 * regress (stop ignoring load-results/):
 *
 *   ARM 1 (stays GREEN): a JS file with a genuine eslint ERROR planted in
 *          backend/load-results/ is IGNORED — `eslint --quiet` exits 0.
 *          Proves the new exclusion takes effect.
 *
 *   ARM 2 (FAILS):       the SAME error-containing file planted in
 *          backend/services/ (real, never-ignored source dir) makes
 *          `eslint --quiet` exit non-zero. Proves the gate still catches
 *          genuine errors in shipped code — the ignore is scoped to the
 *          runtime dir, not a blanket weakening.
 *
 * Targeting the planted paths directly (not `.`) keeps the sentinel fast and
 * isolates it from the rest of the backend tree's lint state, while still
 * exercising the real eslint + real flat-config ignore resolution that the
 * doctrine gate relies on.
 */

import { describe, it, expect, beforeAll, afterEach } from '@jest/globals';
import { spawnSync } from 'node:child_process';
import fs, { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..', '..', '..');
const BACKEND = path.join(REPO_ROOT, 'backend');

// Resolve the eslint CLI the SAME way check-backend-lint-and-format.mjs does:
// direct filesystem probe at backend/ then repo root (hoisted installs).
// require.resolve cannot reach eslint's bin via its "exports" map.
function resolveEslintCli() {
  for (const base of [BACKEND, REPO_ROOT]) {
    const candidate = path.join(base, 'node_modules', 'eslint', 'bin', 'eslint.js');
    if (existsSync(candidate)) {
      return candidate;
    }
  }
  return null;
}

const eslintCli = resolveEslintCli();

// A genuine error under backend/eslint.config.mjs: `'a' + 'b'` trips
// no-useless-concat (error) and the unused `x` trips no-unused-vars (error).
// `--quiet` reports errors only, so this is exactly the shape the doctrine
// gate fails on. Mirrors the planted-error proof in the doctrine check itself.
const ERROR_JS = "const x = 'a' + 'b';\n";

// Plant inside a gitignored runtime dir (load-results/) — must be IGNORED.
const IGNORED_DIR = path.join(BACKEND, 'load-results');
const IGNORED_FILE = path.join(IGNORED_DIR, '_ke6ob_sentinel_artifact.js');

// Plant inside a real, never-ignored source dir (services/) — must be LINTED.
const SOURCE_DIR = path.join(BACKEND, 'services');
const SOURCE_FILE = path.join(SOURCE_DIR, '_ke6ob_sentinel_error.js');

function runEslintQuiet(absFile) {
  // Run from cwd=backend so eslint loads backend/eslint.config.mjs and applies
  // its flat-config `ignores`, exactly like the doctrine gate. Pass the path
  // relative to backend/ so the ignore globs (relative to the config dir) match.
  const rel = path.relative(BACKEND, absFile).split(path.sep).join('/');
  return spawnSync(process.execPath, [eslintCli, rel, '--quiet'], {
    cwd: BACKEND,
    encoding: 'utf8',
  });
}

const maybe = eslintCli ? describe : describe.skip;

beforeAll(() => {
  if (!eslintCli) {
    throw new Error(
      'eslint CLI not found under backend/node_modules or repo-root node_modules. ' +
        'Run `cd backend && npm ci` so this sentinel can exercise the real gate.',
    );
  }
});

afterEach(() => {
  for (const f of [IGNORED_FILE, SOURCE_FILE]) {
    try {
      fs.rmSync(f, { force: true });
    } catch {
      // best-effort cleanup
    }
  }
  // Remove load-results/ only if we created it and it is now empty.
  try {
    if (fs.existsSync(IGNORED_DIR) && fs.readdirSync(IGNORED_DIR).length === 0) {
      fs.rmdirSync(IGNORED_DIR);
    }
  } catch {
    // best-effort cleanup
  }
});

maybe('backend/eslint.config.mjs runtime-artifact ignores (Equoria-ke6ob)', () => {
  it('ARM 1 — an eslint error in load-results/ is IGNORED (eslint --quiet stays green)', () => {
    fs.mkdirSync(IGNORED_DIR, { recursive: true });
    fs.writeFileSync(IGNORED_FILE, ERROR_JS);

    const res = runEslintQuiet(IGNORED_FILE);

    // Exit 0: the path is ignored, so eslint finds nothing to report. (When a
    // file is matched only by an ignore pattern and passed explicitly, eslint
    // exits 0 and prints a "file ignored" warning to stderr — never an error.)
    expect(res.status).toBe(0);
    const out = `${res.stdout ?? ''}\n${res.stderr ?? ''}`;
    expect(out).not.toMatch(/no-useless-concat/);
    expect(out).not.toMatch(/no-unused-vars/);
  });

  it('ARM 2 — the SAME error in services/ FAILS eslint --quiet (gate not weakened)', () => {
    fs.writeFileSync(SOURCE_FILE, ERROR_JS);

    const res = runEslintQuiet(SOURCE_FILE);

    // Non-zero exit and eslint names a real error rule — proves the gate still
    // catches genuine errors in shipped code.
    expect(res.status).not.toBe(0);
    const out = `${res.stdout ?? ''}\n${res.stderr ?? ''}`;
    expect(out).toMatch(/no-useless-concat|no-unused-vars/);
  });

  it('eslint.config.mjs ignores list contains the runtime-dir globs (literal regression guard)', () => {
    const configText = fs.readFileSync(path.join(BACKEND, 'eslint.config.mjs'), 'utf8');
    for (const glob of [
      'load-results/**',
      'test-results/**',
      'coverage/**',
      'coverage-partial/**',
      'coverage-temp/**',
      'coverage-security/**',
      '.jest-cache/**',
    ]) {
      expect(configText).toContain(`'${glob}'`);
    }
  });
});
