/**
 * 🧪 INTEGRATION TEST: Leaderboard Controller — Real Database (canonical-DB safe)
 *
 * Rewritten for Equoria-rofku. The previous version was a legacy empty-test-DB
 * test, incompatible with CLAUDE.md §2 (.env.test → canonical `equoria` DB):
 *   - ran unscoped prisma.<model>.deleteMany({}) in before/afterEach (wiped
 *     all real users/horses/breeds/xpEvents/entries — only FK luck spared them),
 *   - hardcoded breed.id=1 / horse.id=1 (collide with real seeded rows),
 *   - used stale schema fields (gender/color/birthDate) so horse.create threw,
 *     and omitted required User.firstName/lastName,
 *   - asserted absolute global counts (total: 2) impossible against real data.
 *
 * This version coexists with real production data:
 *   - unique TestFixture- fixtures with autogenerated ids and a fixtureColor()
 *     horse (valid colorGenotype/phenotype per Equoria-dm1i),
 *   - extreme metric values so the fixtures deterministically top each board
 *     even among thousands of real rows (Int max is 2_147_483_647),
 *   - relative/structural assertions (fixture at expected rank with correct
 *     derived fields) instead of absolute totals,
 *   - scoped cleanup by captured ids only — never deleteMany({}),
 *   - leaderboard cache invalidated per test (controllers cache 5 min;
 *     Redis is disabled under NODE_ENV=test so only the in-memory cache applies).
 */

import { jest, describe, it, expect, beforeEach, afterEach } from '@jest/globals';

// Strategic mocking: external dependency (logger) only — never business logic/DB.
const mockLogger = { error: jest.fn(), info: jest.fn(), warn: jest.fn(), debug: jest.fn() };
jest.mock('../backend/utils/logger.mjs', () => ({ default: mockLogger }));

import prisma from '../packages/database/prismaClient.mjs';
import { fixtureColor } from '../backend/tests/helpers/fixtureColor.mjs';
import { invalidateCachePattern } from '../backend/utils/cacheHelper.mjs';
import {
  getTopPlayersByLevel,
  getTopPlayersByXP,
  getTopHorsesByEarnings,
} from '../backend/controllers/leaderboardController.mjs';

// Metric values astronomically above any real row so the fixtures top each
// board deterministically. Postgres `integer` max is 2_147_483_647.
const TOP_LEVEL = 1_000_000_000;
const RUNNER_LEVEL = 999_999_999;
const TOP_XP = 1_000_000_000;
const TOP_EARNINGS = 1_000_000_000;

function makeRes() {
  return { json: jest.fn(), status: jest.fn().mockReturnThis() };
}

describe('🏆 INTEGRATION: Leaderboard Controller — canonical-DB safe', () => {
  let userIds = [];
  let horseIds = [];
  let breedIds = [];
  let user1Id;
  let user2Id;
  let horseId;
  let breedId;
  let user1Name;
  let breedName;

  beforeEach(async () => {
    const tag = `${Date.now()}-${Math.floor(Math.random() * 1e6)}`;
    user1Id = `TestFixture-LB-u1-${tag}`;
    user2Id = `TestFixture-LB-u2-${tag}`;
    user1Name = `TestFixture-LB-Alice-${tag}`;
    const user2Name = `TestFixture-LB-Bob-${tag}`;
    breedName = `TestFixture-LB-Breed-${tag}`;

    const breed = await prisma.breed.create({
      data: { name: breedName, description: 'TestFixture breed' },
    });
    breedId = breed.id;

    const user1 = await prisma.user.create({
      data: {
        id: user1Id,
        username: user1Name,
        firstName: 'Test',
        lastName: 'Alice',
        email: `${user1Id}@test.example`,
        password: 'hashedpassword',
        level: TOP_LEVEL,
        xp: 50,
        money: 5000,
      },
    });
    const user2 = await prisma.user.create({
      data: {
        id: user2Id,
        username: user2Name,
        firstName: 'Test',
        lastName: 'Bob',
        email: `${user2Id}@test.example`,
        password: 'hashedpassword',
        level: RUNNER_LEVEL,
        xp: 75,
        money: 3000,
      },
    });

    const horse = await prisma.horse.create({
      data: {
        name: `TestFixture-LB-Star-${tag}`,
        userId: user1.id,
        breedId: breed.id,
        sex: 'Mare',
        dateOfBirth: new Date('2020-01-01'),
        totalEarnings: TOP_EARNINGS,
        ...fixtureColor(),
      },
    });
    horseId = horse.id;

    await prisma.xpEvent.create({
      data: { userId: user1.id, amount: TOP_XP, reason: 'TestFixture-LB' },
    });

    userIds = [user1Id, user2Id];
    horseIds = [horseId];
    breedIds = [breedId];

    // Controllers cache results for 5 min — clear leaderboard keys so the
    // fresh fixtures are visible this test.
    await invalidateCachePattern('leaderboard:*');
    jest.clearAllMocks();
  });

  afterEach(async () => {
    // Scoped cleanup — captured ids only; NEVER deleteMany({}) (CLAUDE.md §2 / Equoria-rofku).
    // FK order: xpEvent (→user) and horse (→user,breed) before user/breed.
    await prisma.xpEvent.deleteMany({ where: { userId: { in: userIds } } });
    await prisma.horse.deleteMany({ where: { id: { in: horseIds } } });
    await prisma.breed.deleteMany({ where: { id: { in: breedIds } } });
    await prisma.user.deleteMany({ where: { id: { in: userIds } } });
    await invalidateCachePattern('leaderboard:*');
    jest.clearAllMocks();
  });

  describe('getTopPlayersByLevel', () => {
    it('ranks the extreme-level fixtures at the top in (level desc, xp desc) order', async () => {
      const res = makeRes();
      await getTopPlayersByLevel({ query: { limit: '10', offset: '0' } }, res);

      expect(res.json).toHaveBeenCalledTimes(1);
      const body = res.json.mock.calls[0][0];
      expect(body.success).toBe(true);
      const { users, pagination } = body.data;

      // Unreachable levels → deterministic ranks 1 and 2 even among real users.
      expect(users[0].userId).toBe(user1Id);
      expect(users[0].rank).toBe(1);
      expect(users[0].name).toBe(user1Name);
      expect(users[0].level).toBe(TOP_LEVEL);
      expect(users[0].xp).toBe(50);
      expect(users[0].money).toBe(5000);

      expect(users[1].userId).toBe(user2Id);
      expect(users[1].rank).toBe(2);
      expect(users[1].level).toBe(RUNNER_LEVEL);

      // Coexists with real data: total is the full user count, not just fixtures.
      expect(pagination.total).toBeGreaterThanOrEqual(2);
      expect(pagination.limit).toBe(10);
      expect(pagination.offset).toBe(0);
    });
  });

  describe('getTopPlayersByXP', () => {
    it('ranks the extreme-XP fixture first by summed xpEvents', async () => {
      const res = makeRes();
      await getTopPlayersByXP({ query: { limit: '10', offset: '0' } }, res);

      const body = res.json.mock.calls[0][0];
      expect(body.success).toBe(true);
      const { users } = body.data;
      expect(users[0].userId).toBe(user1Id);
      expect(users[0].rank).toBe(1);
      expect(users[0].name).toBe(user1Name);
      expect(users[0].totalXp).toBe(TOP_XP);
    });
  });

  describe('getTopHorsesByEarnings', () => {
    it('ranks the extreme-earnings fixture horse first with owner + breed', async () => {
      const res = makeRes();
      await getTopHorsesByEarnings({ query: {} }, res);

      const body = res.json.mock.calls[0][0];
      expect(body.success).toBe(true);
      const { horses } = body.data;
      expect(horses[0].horseId).toBe(horseId);
      expect(horses[0].rank).toBe(1);
      expect(horses[0].earnings).toBe(TOP_EARNINGS);
      expect(horses[0].ownerName).toBe(user1Name);
      expect(horses[0].breedName).toBe(breedName);
    });
  });
});
