/**
 * Performance Test Data Seeding Script
 *
 * This script seeds the database with performance test data including:
 * - Large datasets for load testing
 * - Complex relationships for query performance testing
 * - Realistic data volumes for memory testing
 */

import { pathToFileURL } from 'url';
import prisma from '../db/index.mjs';
import bcrypt from 'bcryptjs';
import logger from '../utils/logger.mjs';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

// Shared horse starter-stats service — the SAME generator the production
// store-purchase path uses. Per-breed mean+std_dev with Box-Muller; clamped
// to [1, 100]; means sum to ~195-200. Random-stat seeds are forbidden:
// they don't exercise the same code paths as real horse data and produce
// false performance numbers.
import { generateStoreStats } from '../services/horseStarterStats.mjs';

// Pre-load the breed-starter-stats JSON so we can filter the breed pool
// down to ONLY breeds that have a profile. The DB may contain test-leftover
// breeds (e.g., "OWASP Test Breed") that have no entry; passing them to
// generateStoreStats correctly throws. The perf seed must skip those rather
// than crashing.
const __dirname = dirname(fileURLToPath(import.meta.url));
const STARTER_STATS_PATH = resolve(__dirname, '..', 'data', 'breedStarterStats.json');
const BREED_NAMES_WITH_PROFILES = new Set(
  Object.keys(JSON.parse(readFileSync(STARTER_STATS_PATH, 'utf8'))),
);

// Performance test data configuration
const PERFORMANCE_DATA_CONFIG = {
  users: 100,
  horsesPerUser: 20,
  showsPerUser: 10,
  competitionResultsPerHorse: 50,
  groomsPerUser: 5,
  trainingSessionsPerHorse: 30,
};

/**
 * Generate performance test users
 */
async function seedPerformanceUsers() {
  logger.info('🔄 Seeding performance test users...');

  const users = [];
  // Use configurable bcrypt rounds (default: 12 for 2025 security standards)
  const saltRounds = parseInt(process.env.BCRYPT_SALT_ROUNDS || '12', 10);
  const hashedPassword = await bcrypt.hash('testpassword123', saltRounds);

  for (let i = 1; i <= PERFORMANCE_DATA_CONFIG.users; i++) {
    users.push({
      email: `perftest${i}@equoria.com`,
      username: `perfuser${i}`,
      password: hashedPassword,
      firstName: 'Performance',
      lastName: `User${i}`,
      money: 10000,
      xp: Math.floor(Math.random() * 5000),
      level: Math.floor(Math.random() * 20) + 1,
      settings: {
        notifications: true,
        theme: 'default',
      },
    });
  }

  await prisma.user.createMany({
    data: users,
    skipDuplicates: true,
  });

  logger.info(`✅ Created ${users.length} performance test users`);
  return users;
}

/**
 * Generate performance test horses
 */
async function seedPerformanceHorses() {
  logger.info('🔄 Seeding performance test horses...');

  const users = await prisma.user.findMany({
    where: {
      email: {
        startsWith: 'perftest',
      },
    },
  });

  // Filter to breeds that have a starter-stats profile in
  // breedStarterStats.json. Skips test-leftover breeds (e.g. "OWASP Test
  // Breed") that would cause generateStoreStats to throw.
  const allBreeds = await prisma.breed.findMany();
  const breeds = allBreeds.filter(b => BREED_NAMES_WITH_PROFILES.has(b.name));
  if (breeds.length === 0) {
    throw new Error(
      'seedPerformanceHorses: no breeds in DB have a starter-stats profile. ' +
        'Run `npm run seed` (5 canonical breeds) or `npm run seed:breeds` first.',
    );
  }
  logger.info(
    `   using ${breeds.length} breed${breeds.length === 1 ? '' : 's'} with starter-stats profiles ` +
      `(skipped ${allBreeds.length - breeds.length} test-leftover breed${allBreeds.length - breeds.length === 1 ? '' : 's'})`,
  );
  const horses = [];

  for (const user of users) {
    for (let i = 1; i <= PERFORMANCE_DATA_CONFIG.horsesPerUser; i++) {
      const breed = breeds[Math.floor(Math.random() * breeds.length)];
      const age = Math.floor(Math.random() * 20) + 1;

      // Schema fields (chunk-B fix 2026-04-30): older seed wrote
      // `health`/`bonding`/`stress`/`stats: {…}`/`traits: {…}` — none match
      // current Horse schema. Stats are TOP-LEVEL Int columns; epigenetic
      // data lives on `epigeneticModifiers`; health/bond/stress are
      // `healthStatus` (String), `bondScore` (Int), `stressLevel` (Int).
      //
      // Stats are generated by the SAME canonical pipeline the store
      // purchase uses (services/horseStarterStats.mjs::generateStoreStats).
      // This ensures perf tests measure realistic horse data: per-breed
      // mean + std_dev sampled via Box-Muller, clamped [1, 100], summing
      // to ~195-200. Random stats independent of breed — the prior
      // approach — would skew perf numbers and hide breed-derived
      // computation costs.
      const starterStats = generateStoreStats(breed.name);
      horses.push({
        name: `PerfHorse${user.id}_${i}`,
        sex: Math.random() > 0.5 ? 'stallion' : 'mare',
        dateOfBirth: new Date(Date.now() - age * 7 * 24 * 60 * 60 * 1000), // Age in weeks
        breedId: breed.id,
        userId: user.id,
        healthStatus: 'Excellent',
        bondScore: Math.floor(Math.random() * 50) + 50,
        stressLevel: Math.floor(Math.random() * 30),
        horseXp: Math.floor(Math.random() * 1000),
        ...starterStats,
        disciplineScores: {
          racing: Math.floor(Math.random() * 100),
          dressage: Math.floor(Math.random() * 100),
          showJumping: Math.floor(Math.random() * 100),
          crossCountry: Math.floor(Math.random() * 100),
          western: Math.floor(Math.random() * 100),
          gaited: Math.floor(Math.random() * 100),
        },
        epigeneticModifiers: { positive: [], negative: [], hidden: [] },
        taskLog: {},
        lastGroomed: new Date(),
      });
    }
  }

  // Create horses in batches to avoid memory issues
  const batchSize = 100;
  for (let i = 0; i < horses.length; i += batchSize) {
    const batch = horses.slice(i, i + batchSize);
    await prisma.horse.createMany({
      data: batch,
      skipDuplicates: true,
    });
  }

  logger.info(`✅ Created ${horses.length} performance test horses`);
  return horses.length;
}

/**
 * Generate performance test shows and competitions
 */
async function seedPerformanceShows() {
  logger.info('🔄 Seeding performance test shows...');

  const users = await prisma.user.findMany({
    where: {
      email: {
        startsWith: 'perftest',
      },
    },
  });

  const disciplines = [
    'racing',
    'dressage',
    'showJumping',
    'crossCountry',
    'western',
    'gaited',
    'endurance',
    'eventing',
  ];

  const shows = [];

  for (const user of users) {
    for (let i = 1; i <= PERFORMANCE_DATA_CONFIG.showsPerUser; i++) {
      const discipline = disciplines[Math.floor(Math.random() * disciplines.length)];
      const showDate = new Date(Date.now() + Math.random() * 30 * 24 * 60 * 60 * 1000);

      shows.push({
        // Show.name is @unique; user.id is a UUID so this is collision-free.
        name: `Performance Show ${user.id}_${i}`,
        discipline,
        // Schema fields (chunk-B fix 2026-04-30, was schema-drift from
        // pre-21R refactor): runDate (was `date`), hostUserId (was `hostId`),
        // levelMin/Max + entryFee required, status enum is open|closed|
        // executing|completed (was free-form 'upcoming'), location and
        // currentEntries do not exist on Show.
        levelMin: 1,
        levelMax: 20,
        entryFee: Math.floor(Math.random() * 200) + 50,
        prize: Math.floor(Math.random() * 5000) + 1000,
        runDate: showDate,
        maxEntries: Math.floor(Math.random() * 50) + 20,
        status: 'open',
        hostUserId: user.id,
      });
    }
  }

  await prisma.show.createMany({
    data: shows,
    skipDuplicates: true,
  });

  logger.info(`✅ Created ${shows.length} performance test shows`);
  return shows;
}

/**
 * Generate performance test competition results
 */
async function seedPerformanceCompetitionResults() {
  logger.info('🔄 Seeding performance test competition results...');

  const horses = await prisma.horse.findMany({
    where: {
      user: {
        email: {
          startsWith: 'perftest',
        },
      },
    },
    include: {
      user: true,
    },
  });

  const shows = await prisma.show.findMany({
    where: {
      // Show.user-relation is `hostUser` (FK: hostUserId), not `host`.
      // Matches the corresponding fix in the cleanup block above.
      hostUser: {
        email: {
          startsWith: 'perftest',
        },
      },
    },
  });

  const results = [];

  for (const horse of horses) {
    const numResults = Math.min(PERFORMANCE_DATA_CONFIG.competitionResultsPerHorse, shows.length);

    const selectedShows = shows.sort(() => 0.5 - Math.random()).slice(0, numResults);

    for (const show of selectedShows) {
      const placement = Math.floor(Math.random() * 10) + 1;
      const score = Math.floor(Math.random() * 1000) + 500;
      const prizeWon = placement <= 3 ? Math.floor(show.prize / placement) : 0;

      results.push({
        horseId: horse.id,
        showId: show.id,
        // Schema fields (chunk-B fix 2026-04-30): CompetitionResult has no
        // direct userId — reach the user via horse.user. placement is a
        // String? (denormalized rank label like '1st', not an integer).
        // Required: showName + runDate (was 'competitionDate' field name).
        placement: String(placement),
        score,
        prizeWon,
        discipline: show.discipline,
        runDate: new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000),
        showName: show.name,
      });
    }
  }

  // Create results in batches
  const batchSize = 500;
  for (let i = 0; i < results.length; i += batchSize) {
    const batch = results.slice(i, i + batchSize);
    await prisma.competitionResult.createMany({
      data: batch,
      skipDuplicates: true,
    });
  }

  logger.info(`✅ Created ${results.length} performance test competition results`);
  return results.length;
}

/**
 * Generate performance test grooms
 */
async function seedPerformanceGrooms() {
  logger.info('🔄 Seeding performance test grooms...');

  const users = await prisma.user.findMany({
    where: {
      email: {
        startsWith: 'perftest',
      },
    },
  });

  const personalities = ['calm', 'energetic', 'methodical'];
  const specialties = ['foalCare', 'generalGrooming', 'competition'];
  const grooms = [];

  for (const user of users) {
    for (let i = 1; i <= PERFORMANCE_DATA_CONFIG.groomsPerUser; i++) {
      const personality = personalities[Math.floor(Math.random() * personalities.length)];
      const specialty = specialties[Math.floor(Math.random() * specialties.length)];

      // Schema fields (chunk-B fix 2026-04-30): the column is `speciality`
      // (sic — typo preserved in schema), and `skillLevel` is a String enum
      // (novice|beginner|...) not a number.
      const skillLevels = ['novice', 'beginner', 'intermediate', 'expert', 'master'];
      grooms.push({
        name: `PerfGroom${user.id}_${i}`,
        personality,
        speciality: specialty,
        skillLevel: skillLevels[Math.floor(Math.random() * skillLevels.length)],
        experience: Math.floor(Math.random() * 1000),
        userId: user.id,
        isActive: true,
        careerWeeks: Math.floor(Math.random() * 50),
        level: Math.floor(Math.random() * 10) + 1,
      });
    }
  }

  await prisma.groom.createMany({
    data: grooms,
    skipDuplicates: true,
  });

  logger.info(`✅ Created ${grooms.length} performance test grooms`);
  return grooms.length;
}

/**
 * Generate performance test training sessions
 */
async function seedPerformanceTrainingSessions() {
  logger.info('🔄 Seeding performance test training sessions...');

  const horses = await prisma.horse.findMany({
    where: {
      user: {
        email: {
          startsWith: 'perftest',
        },
      },
    },
  });

  const disciplines = ['racing', 'dressage', 'showJumping', 'crossCountry', 'western', 'gaited'];
  const sessions = [];

  for (const horse of horses) {
    for (let i = 1; i <= PERFORMANCE_DATA_CONFIG.trainingSessionsPerHorse; i++) {
      const discipline = disciplines[Math.floor(Math.random() * disciplines.length)];
      const sessionDate = new Date(Date.now() - Math.random() * 365 * 24 * 60 * 60 * 1000);

      sessions.push({
        // Schema fields (chunk-B fix 2026-04-30): TrainingLog has only
        // discipline + trainedAt + horseId. Older seed wrote skillImprovement
        // and notes which never existed on this model.
        horseId: horse.id,
        discipline,
        trainedAt: sessionDate,
      });
    }
  }

  // Create sessions in batches
  const batchSize = 1000;
  for (let i = 0; i < sessions.length; i += batchSize) {
    const batch = sessions.slice(i, i + batchSize);
    await prisma.trainingLog.createMany({
      data: batch,
      skipDuplicates: true,
    });
  }

  logger.info(`✅ Created ${sessions.length} performance test training sessions`);
  return sessions.length;
}

/**
 * Main performance data seeding function
 */
async function seedPerformanceData() {
  try {
    logger.info('🚀 Starting performance data seeding...');
    logger.info('=====================================');

    // Clean existing performance test data
    logger.info('🧹 Cleaning existing performance test data...');
    // CompetitionResult has no direct `user` relation — only `horse` and
    // `show`. Reach the user via horse.user, matching the trainingLog clean
    // immediately below. (Equoria-3iyk Phase 1c — schema drift from a
    // previous refactor that removed CompetitionResult.userId.)
    await prisma.competitionResult.deleteMany({
      where: {
        horse: {
          user: {
            email: {
              startsWith: 'perftest',
            },
          },
        },
      },
    });

    await prisma.trainingLog.deleteMany({
      where: {
        horse: {
          user: {
            email: {
              startsWith: 'perftest',
            },
          },
        },
      },
    });

    await prisma.groom.deleteMany({
      where: {
        user: {
          email: {
            startsWith: 'perftest',
          },
        },
      },
    });

    await prisma.horse.deleteMany({
      where: {
        user: {
          email: {
            startsWith: 'perftest',
          },
        },
      },
    });

    // Show's user relation is `hostUser` (FK: hostUserId), not `host`.
    // Equoria-3iyk Phase 1c (continuation of competitionResult fix).
    await prisma.show.deleteMany({
      where: {
        hostUser: {
          email: {
            startsWith: 'perftest',
          },
        },
      },
    });

    await prisma.user.deleteMany({
      where: {
        email: {
          startsWith: 'perftest',
        },
      },
    });

    // Seed performance test data
    await seedPerformanceUsers();
    await seedPerformanceHorses();
    await seedPerformanceShows();
    await seedPerformanceCompetitionResults();
    await seedPerformanceGrooms();
    await seedPerformanceTrainingSessions();

    logger.info('✅ Performance data seeding completed successfully!');
    logger.info('📊 Performance test database ready for load testing');
  } catch (error) {
    logger.error('❌ Performance data seeding failed:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run seeding if this script is executed directly. Use pathToFileURL to
// correctly compare on Windows (where `process.argv[1]` uses backslashes
// but `import.meta.url` uses URL-encoded forward slashes — the simple
// `file://${argv[1]}` template never matches on Windows, silently making
// the script a no-op when invoked via `node seed/seedPerformanceData.mjs`).
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  seedPerformanceData()
    .then(() => {
      console.log('✅ Performance data seeding completed');
      process.exit(0);
    })
    .catch(error => {
      console.error('❌ Performance data seeding failed:', error);
      process.exit(1);
    });
}

export { seedPerformanceData };
