/**
 * Profile Activity Feed E2E Smoke Test
 *
 * Verifies the /profile activity feed renders real backend data — specifically
 * XP events generated by training — with production parity (no bypass headers).
 *
 * The activity feed is backed by GET /api/v1/users/:id/activity which returns
 * XpEvent rows. A fresh user who has trained at least once will have entries.
 *
 * Flow:
 *   1. Register a new player and complete onboarding (provides a starter horse)
 *   2. Train the horse via POST /api/v1/training/train to generate a real XP event
 *   3. Directly verify the API returns at least one activity entry with real fields
 *   4. Navigate to /profile
 *   5. Assert the activity-feed section is visible
 *   6. Assert at least one [data-testid="activity-feed-item"] is rendered (real data)
 *   7. Verify entries do not contain hardcoded mock strings
 *
 * Issue: Equoria-7e6v
 */

import { test, expect } from '@playwright/test';
// @ts-expect-error — JS module without .d.ts; import works at runtime via Node.
import prisma from '../../../packages/database/prismaClient.mjs';
import {
  csrfRequest,
  expectOk,
  installProductionParityNetworkGuard,
  registerAndCompleteOnboarding,
  unwrapData,
} from './support/prodParity';

test.afterAll(async () => {
  try {
    await prisma.horse.deleteMany({
      where: { name: { startsWith: 'ActivityTest Horse' } },
    });
  } finally {
    await prisma.$disconnect();
  }
});

test('profile activity feed renders real XP event data with no bypass headers', async ({
  page,
}) => {
  const guard = installProductionParityNetworkGuard(page);
  const suffix = `${Date.now()}_act`;

  // Step 1: Register fresh player — also sets up a starter horse and an onboarding XP event
  await registerAndCompleteOnboarding(page, suffix, `ActivityTest Horse ${suffix}`);

  // Step 2: Fetch the authenticated user's profile to get the user ID
  const profileJson = await expectOk(
    await page.request.get('/api/v1/auth/profile'),
    'GET /api/auth/profile'
  );
  const profile = unwrapData<{ user: { id: string } }>(profileJson);
  const userId = profile.user.id;
  expect(userId, 'User ID must be a non-empty string').toBeTruthy();

  // Step 3: Train the horse to ensure at least one XP event is recorded in the DB.
  // Training always creates an XP event regardless of cooldown state.
  const horsesJson = await expectOk(await page.request.get('/api/v1/horses'), 'GET /api/horses');
  const horses = unwrapData<Array<{ id: number; name: string }>>(horsesJson);
  const starterHorse = horses.find((h) => h.name.startsWith('ActivityTest Horse'));
  expect(starterHorse, 'Starter horse must be findable by name prefix').toBeTruthy();
  const starterHorseId = Number(starterHorse!.id);

  // Train — the response may be 200 (success) or 400 (cooldown active, already trained today).
  // Either way, the *act of registration + onboarding* itself likely seeded XP events.
  // We try training first and proceed regardless.
  await csrfRequest(page, 'POST', '/api/v1/training/train', {
    horseId: starterHorseId,
    discipline: 'Dressage',
  });

  // Step 4: Verify via direct API call that the activity feed has real entries.
  // This confirms the backend returns data before we assert on the UI rendering.
  const activityJson = await expectOk(
    await page.request.get(`/api/v1/users/${userId}/activity`),
    `GET /api/v1/users/${userId}/activity`
  );
  const activityItems = unwrapData<
    Array<{
      id: string | number;
      type: string;
      description: string;
      timestamp: string;
      metadata?: Record<string, unknown>;
    }>
  >(activityJson);

  // The API returns recent XP events; a fresh user has at least the onboarding XP grant
  expect(Array.isArray(activityItems), 'Activity endpoint must return an array').toBe(true);
  expect(
    activityItems.length,
    'Activity feed must contain at least 1 real entry (onboarding or training XP)'
  ).toBeGreaterThan(0);

  const firstItem = activityItems[0];

  // Assert the entry has real dynamic fields — not hardcoded mock data
  expect(typeof firstItem.id, 'Activity item must have an id').not.toBe('undefined');
  expect(typeof firstItem.type, 'Activity item must have a type').toBe('string');
  expect(firstItem.type.length, 'Activity type must not be empty').toBeGreaterThan(0);
  expect(typeof firstItem.timestamp, 'Activity item must have a timestamp').toBe('string');
  expect(new Date(firstItem.timestamp).getTime(), 'Timestamp must be a valid date').not.toBeNaN();

  // Confirm no mock/placeholder strings leaked into real data
  const mockMarkers = ['TODO', 'MOCK_', 'allMockHorses', 'mockSummary', 'hardcoded'];
  for (const marker of mockMarkers) {
    expect(
      JSON.stringify(firstItem).includes(marker),
      `Activity item must not contain mock marker "${marker}"`
    ).toBe(false);
  }

  // Step 5: Navigate to /profile and confirm the page loads cleanly
  const profilePageSettled = page.waitForResponse(
    (response) =>
      response.url().includes(`/api/v1/users/${userId}/activity`) &&
      response.request().method() === 'GET'
  );
  await page.goto('/profile', { waitUntil: 'domcontentloaded' });
  await profilePageSettled;

  // Step 6: Assert activity-feed section is visible
  const feedEl = page.locator('[data-testid="activity-feed"]').first();
  await feedEl.waitFor({ state: 'visible' });
  await expect(feedEl).toBeVisible();

  // Step 7: Assert at least one real activity-feed-item is present (not empty state)
  // The ProfilePage uses maxItems={3} so up to 3 items are shown.
  const feedItems = page.locator('[data-testid="activity-feed-item"]');
  await expect
    .poll(
      async () => {
        return feedItems.count();
      },
      {
        timeout: 8000,
        message: 'Expected at least 1 activity-feed-item to appear on the /profile page',
      }
    )
    .toBeGreaterThan(0);

  // Confirm none of the rendered items contain placeholder text
  const feedText = await feedEl.innerText();
  for (const placeholder of ['Loading...', 'TODO', 'MOCK_']) {
    expect(
      feedText.includes(placeholder),
      `Activity feed must not show placeholder text "${placeholder}"`
    ).toBe(false);
  }

  guard.assertClean();
});
